### PR TITLE
memorable password login fix

### PR DESCRIPTION
**Pull request by juliangums**
login with memorable password still seemed to only work sometimes. however, repeating the click process seems to work

### CODE REVIEW

**Comment by carpii** [comment]
Hi @juliangums,

Were you having these problems prior to the weekend? 
master branch is currently getting a timeout for me too, but when I check the Barclays site, it seems like it's due to Barclays demanding I select a new memorable passcode

Hopefully not as a result of all the debug runs I did when trying to fix it :p

**Comment by carpii** [comment]
Ok I reset my passcode and my branch still times out.

Can confirm your fix is working, although must admit I don't fully understand why :-)

Good job though, thanks

**Comment by juliangums** [comment]
@carpii 
yeah dude it's a really weird one... haven't used barclayscrape in a while. tried it for the first time in a few weeks yesterday with the new fixes and i was logged in but then couldn't repeat it. so i gave it a few more goes and had a 1:5 chance. debug images looked like everything is filled in properly so i thought ok let me just wait 5 seconds before hitting the submit button. didn't work. then i just tried hitting it again if the page fails to load. i really have no idea why but it's working 100% of times now. i was thinking i might have some different content served as i have an offshore account cause i live in jersey but if you're having the same issues i'm glad i could help. hope @russss is gonna merge this
cheers

**Comment by carpii** [comment]
@juliangums Yeah, I had terrible problems trying to just populate the passcode dropdown boxes from casper. 
Barclays seem to have moved to angular, and everything is very very dynamic. Doesn't surprise me this workaround is needed. I'm expecting a few more breaks next weekend when they have said they'll doing more maintenance.

The cat and mouse game continues ;-)

**Comment by russss** [comment]
I really should care more about finding a less hacky fix but I have neither the time nor the ability to test it. So I'll allow it. :)

**Pull request merged**
