### PR TITLE
Restore functionality to login via passcode and password

### PR DESCRIPTION
**Pull request by carpii**

### CODE REVIEW

**Comment by carpii** [comment]
@Sc0th, @juliangums - not sure if either of you still use this library, and still have an account which is configured to support passcode login?

If so, I'd really appreciate any testing you can offer thanks

**Comment by juliangums** [comment]
@carpii unfortunetely not. Don't have a Barclays account anymore

**Comment by Sc0th** [comment]
Will try to fire it up this weekend.

**Comment by carpii** [comment]
@russss Any chance of getting this merged please? 

It appears to be robust and does not affect otp or motp, but would like it merged before I move onto the next set of features I have planned

Cheers

**Comment by russss** [comment]
I'm not ignoring you - I'm currently dealing with a family emergency so it might be a week or so before I can get round to merging this. Seems fine at a quick glance though!

**Comment by carpii** [comment]
Not a problem @russss, hope things work out ok.

I wasn't sure if you get a notification of pull requests, so I tagged you with a note

**Pull request merged**
